### ISSUE TITLE
如何制作MacOS引导U盘？

### ISSUE THREAD

**Issue by Case3y** [huichenmoyan/ThinkPad-E480-Hackintosh#4]
你好，感谢作者分享了这个EFI。我想问一下你是如何制作MacOS引导U盘的，我使用了[gibMacOS](https://github.com/corpnewt/gibMacOS)这个工具制作了引导盘，替换EFI后直接无法引导，还是进入了Windows

**Comment by huichenmoyan** [comment]
![image](https://github.com/user-attachments/assets/5407bf45-71f8-4f77-aeb1-c50d9aa58e86)
